### ISSUE TITLE
Question about the flow-based model.

### ISSUE THREAD

**Issue by ChihchengHsieh** [chaiyujin/glow-pytorch#1]
Hello, 

It's my first time to touch the flow-based model, and still wondering the function of encoder and decoder. 

If I do something like this 

`
out = reverse_flow(normal_flow(img))
`

then, the out will be exactly the same as image?

**Comment by chaiyujin** [comment]
Hi, I am also a rookie.
I think, the out should be almost same as original image, according to my experiments.
The module [Split2d] performs like a pooling layer. At the reverse phase, module [Split2d] will introduce some noises, since it need to sample from a multi-variant Gaussian distribution.
Thus, it seems to be impossible to be exactly same.
